### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by anson39f** [smuyyh/BookReader#117]

**Comment by anson39f** [comment]
标题的文字消失不见了，在断开WIFI传书之后

**Comment by anson39f** [comment]
标题的文字消失不见了，在断开WIFI传书之后

**Comment by smuyyh** [comment]
有截图麽？你是说Toolbar？

**Comment by anson39f** [comment]
![screenshot_2017-03-20-14-46-03-299_com justwayward reader](https://cloud.githubusercontent.com/assets/18600006/24091142/27e4bbca-0d81-11e7-8a2c-77eca8cebce6.png)
滑动的标题栏

**Comment by smuyyh** [comment]
好吧…  我试了一下好像没发生这问题，我再看看

**Comment by anson39f** [comment]
那是说错，是在全换日夜间模式之后。
