### ISSUE TITLE
全面屏手机，点击中间弹出菜单，布局会上移

### ISSUE THREAD

**Issue by MrBoudar** [smuyyh/BookReader#218]
全面屏手机，点击中间弹出菜单，布局会上移,这个需要怎么适配下

**Comment by smuyyh** [comment]
截图看看？

**Comment by MrBoudar** [comment]
![20180907_170944](https://user-images.githubusercontent.com/17286695/45210378-fbef5b00-b2c1-11e8-9797-d6a5b38fc0a9.gif)
ok,你看看效果，掌阅和微信阅读没有问题

**Comment by smuyyh** [comment]
可能是因为切换View.setSystemVisibility 引起的，可以尝试修改下试试

**Comment by MrBoudar** [comment]
感觉不行，退出全屏，必须有Full_screen的属性，因为要同步展示状态栏，有这个属性，必然会布局上移的，好像没啥办法，您有时间研究看看唄，我也是作安卓开发的，遇到了这个问题，嘿嘿，我暂时不用这个属性了，不会布局上移了，但是，和掌阅的效果还是有点差距.

**Comment by ALguojian** [comment]
状态栏透明之后，现实和隐藏都不会影响高度了吧

**Comment by MrBoudar** [comment]
@ALguojian 跟透明没有关系的，SYSTEM_UI_FLAG_FULLSCREEN 只要有这个属性，全面屏手机布局必然会抖动上移，我现在解决方案是没有用这个属性，但是效果不好啊，状态栏相当于一直显示着了，不知道微信，多看，掌阅是怎么实现的

**Comment by xincubate** [comment]
其实我觉得一直让他显示出来就好了。。。。只要高度不发生变化，是没有关系的。。。通过修改状态栏的底色，能做到比较好的体验。。。可以试试https://github.com/xincubate/EasyReader
在任阅的基础上做了一些简单的优化

**Comment by MrBoudar** [comment]
> 其实我觉得一直让他显示出来就好了。。。。只要高度不发生变化，是没有关系的。。。通过修改状态栏的底色，能做到比较好的体验。。。可以试试https://github.com/xincubate/EasyReader
> 在任阅的基础上做了一些简单的优化

一直显示不太好吧，我现在虽然也是一直显示的，感觉不好吧

**Comment by xincubate** [comment]
> > 其实我觉得一直让他显示出来就好了。。。。只要高度不发生变化，是没有关系的。。。通过修改状态栏的底色，能做到比较好的体验。。。可以试试https://github.com/xincubate/EasyReader
> > 在任阅的基础上做了一些简单的优化
> 
> 一直显示不太好吧，我现在虽然也是一直显示的，感觉不好吧

你可以看下微信阅读、QQ阅读这种主流的阅读器，只要做好沉浸式视觉没什么不好的。我感觉

**Comment by MrBoudar** [comment]
> 阅读

微信阅读，掌阅的我都看了啊，人家默认没有显示状态栏的
