### ISSUE TITLE
请问左右翻页是怎么实现的呢

### ISSUE THREAD

**Issue by ZihanType** [smuyyh/BookReader#232]
我现在用Flutter写一个小说阅读器，不会左右翻页，不知道怎么切分一段文本，分页显示。我Android学得不太好，看源码没看懂，可以指点我一下吗？

**Comment by liumengbiao** [comment]
if (status == BookStatus.NO_NEXT_PAGE) {
                            ToastUtils.showSingleToast("没有下一页啦");
                            return false;
                        } else if (status == BookStatus.LOAD_SUCCESS) {
                          // 这里就是翻页的关键代码，在BaseReadView 这个类中调用，子类实现。先执行动画，在实现下一个cavas。你可以看看子类怎么实现抽象方法‘abortAnimation()’的
                            abortAnimation();
                            pagefactory.onDraw(mNextPageCanvas);
                        } else {
                            return false;
                        }

**Comment by liumengbiao** [comment]
//  这几个方法的实现，建议看一下        
       drawCurrentPageArea(canvas);
        drawNextPageAreaAndShadow(canvas);
        drawCurrentPageShadow(canvas);
        drawCurrentBackArea(canvas);

**Comment by ZihanType** [comment]
谢谢指点，我会好好阅读源码的。

刘孟彪 <notifications@github.com> 于2019年5月28日周二 下午4:11写道：
