### ISSUE TITLE
Android9.0版本适配

### ISSUE THREAD

**Issue by gordanxu** [smuyyh/BookReader#237]
canvas.clipPath(mPath0, Region.Op.XOR);这句代码在Android9.0上显示过时了，而且还不能用，用的话会导致APK直接挂掉，目前我想到的解决办法是用 canvas.clipOutPath(mPath0); 替代，不知道作者有其它更换的解决办法没有？希望帮忙解决，谢谢~

**Comment by jack320** [comment]
同问~~~

**Comment by 390057892** [comment]
可以看看这个，在作者的基础上进行了改进，仿真动画适配了安卓9。[Reader](https://github.com/390057892/reader)

**Comment by smuyyh** [comment]
以上
