### ISSUE TITLE
update

### ISSUE THREAD

**Issue by Ayman-SHaaban-ELsayed** [smuyyh/BookReader#252]
need update gradle files and code ,please🌹

**Comment by smuyyh** [comment]
done

**Comment by Ayman-SHaaban-ELsayed** [comment]
thanks so much🌹

**Comment by smuyyh** [comment]
I updated the gradle and mainfest 2 days ago , and it can run normally.

however, the api request used in the project was acquired through packet capturing long ago and has been deprecated, which will get blank view.

so, this project can no longer be maintained
