### ISSUE TITLE
怎么实现效果切换？

### ISSUE THREAD

**Issue by Sabirjan** [smuyyh/BookReader#96]
ReadActivity里面怎么实现翻页效果切换。你把它放在设置里面，但是我想放在阅读页面。。。
切换好像很多东西重新初始化。。。还是不行

**Comment by smuyyh** [comment]
切换的时候  ReadView要重新初始化。然后加载章节

**Comment by Sabirjan** [comment]
然后一个问题：下载的图书清理缓存就没了....这个希望不要保存到缓存区

**Comment by smuyyh** [comment]
恩，确实。后面抽时间改过来~
